AllCops:
  RunRailsCops: true
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'lib/old_import.rb'
    - 'lib/twitter_bot.rb'
    - 'lib/twitter_reader.rb'
    - 'bin/**/*'

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/LineLength:
  Max: 180

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/PerceivedComplexity:
  Max: 11

Metrics/MethodLength:
  Max: 30

Metrics/ClassLength:
  Max: 135

Style/AsciiComments:
  Enabled: false

Style/TrivialAccessors:
  Enabled: false
