- '^[0-9-]{3,}'
- '^тел'
- 'телефон'
- 'звонить'
- 'retweet'
- 'прода(ю|м|дим)'
- 'купл(ю|им)'
- 'устанавливайте'
- 'сда(м|ю|дим)'
- 'приложение'
- 'RT'
- 'тест'
- 'привет'
- 'козёл'
- 'геморой'
- 'джигурда'
- 'retweet'
- 'советуй'
- 'iPhone'
- 'iPad'
- 'мессенджер'
- 'меняю'
- '^РТ'
- 'въебал.*?(\s|$)'
